### ISSUE TITLE
Can you specify a camera.xxx from home-assistant?

### ISSUE THREAD

**Issue by gieljnssns** [asmirnou/watsor-hassio-addons#1]
Can you specify a `camera.xxx` entity from home-assistant?
I'm using Netatmo camera's in home-assistant, and they not provide an url to watch them..

**Comment by asmirnou** [comment]
Yes, Watsor exposes video stream in Motion JPEG format, if the detector is **not** turned off via MQTT. You need to define the camera in HA [as follows](https://github.com/asmirnou/watsor-ha-demo/blob/master/config/cameras.yaml#L1-L4) and then refer it as `camera.xxx`.

**Comment by gieljnssns** [comment]
Sorry, I was not clear, I mean specify a HA-camera in the `watsor/config/config.yaml` like this:
```
cameras:
  - camera1:
      width: 640
      height: 480
      input: camera.xxx
      #output: !ENV "${HOME}/Videos/camera1.m3u8"
      #mask: camera1.png
      #detect: []
      #ffmpeg: []
  - ...
```
